
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASTERISCO ID IGUAL NUMERO SLASH\n    conversion : cantidadDivisa ASTERISCO tasaCambio\n               | cantidadDivisa SLASH tasaCambio\n    \n    cantidadDivisa : NUMERO\n                   | ID\n    \n    tasaCambio : NUMERO\n    '
    
_lr_action_items = {'NUMERO':([0,5,6,],[3,8,8,]),'ID':([0,],[4,]),'$end':([1,7,8,9,],[0,-1,-5,-2,]),'ASTERISCO':([2,3,4,],[5,-3,-4,]),'SLASH':([2,3,4,],[6,-3,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'conversion':([0,],[1,]),'cantidadDivisa':([0,],[2,]),'tasaCambio':([5,6,],[7,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> conversion","S'",1,None,None,None),
  ('conversion -> cantidadDivisa ASTERISCO tasaCambio','conversion',3,'p_conversion','views.py',60),
  ('conversion -> cantidadDivisa SLASH tasaCambio','conversion',3,'p_conversion','views.py',61),
  ('cantidadDivisa -> NUMERO','cantidadDivisa',1,'p_cantidadDivisa','views.py',77),
  ('cantidadDivisa -> ID','cantidadDivisa',1,'p_cantidadDivisa','views.py',78),
  ('tasaCambio -> NUMERO','tasaCambio',1,'p_tasaCambio','views.py',84),
]
